"""Soil Stamp Antonov — reproducible plate-load test analysis."""

from .analysis import (
    PairingResolution,
    calculate_moduli_for_test,
    compare_groups,
    deformation_work,
    estimate_moduli,
    fit_segmented_pcr,
    group_mean_curve,
    hysteresis_metrics,
    resolve_pairing_design,
)
from .methodology import (
    ModulusMethodProfile,
    ModulusOverrides,
    ModulusResolution,
    get_modulus_profile,
    modulus_profile_definitions,
    modulus_profile_ids,
    parse_pressure_range,
    resolve_modulus_method,
)
from .data import (
    AuditTrail,
    apply_settlement_correction,
    classify_branches,
    failure_summary,
    prepare_measurements,
    validate_measurements,
)
from .io import parse_decimal, read_protocol, read_protocol_excel
from .indicators import (
    INDICATOR_AGGREGATION_COLUMNS,
    SETTLEMENT_AGGREGATIONS,
    SETTLEMENT_MISSING_CHANNEL_POLICIES,
    evaluate_indicator_verification,
    fit_indicator_plane,
    indicator_aggregation_frame,
    indicator_audit_frame,
    indicator_event_frame,
    indicator_passport_frame,
    process_indicator_frame,
    resolve_indicator_passport,
    resolve_settlement_aggregation,
)
from .provenance import (
    build_provenance,
    metrology_evaluations_from_passports,
    passport_completeness,
)
from .manual_entry_adapter import (
    ManualExperimentSource,
    ManualInputBundle,
    adapt_manual_draft,
)
from .manual_entry_models import (
    MANUAL_DRAFT_SCHEMA_V1_0,
    MANUAL_DRAFT_SCHEMA_V1_1,
    MANUAL_DRAFT_SCHEMA_VERSION,
    ManualAuditEvent,
    ManualDraft,
    ManualIndicatorPassport,
    ManualLegacyIndicatorCommon,
    ManualPassport,
    ManualPoint,
    ManualReinforcement,
    migrate_manual_draft_payload,
)
from .manual_entry_validation import ManualValidationResult, validate_manual_draft
from .sources import ExcelExperimentSource, ExperimentSource
from .schema import (
    CorrectionRecord,
    Experiment,
    ExperimentPoint,
    IndicatorPassport,
    IndicatorProcessingResult,
    MeasuredPoint,
    ProcessingConfig,
    Project,
    ProvenanceRecord,
    RawCell,
    RawRow,
    VERSION,
)

__all__ = [
    "AuditTrail",
    "apply_settlement_correction",
    "classify_branches",
    "calculate_moduli_for_test",
    "compare_groups",
    "CorrectionRecord",
    "deformation_work",
    "estimate_moduli",
    "ExcelExperimentSource",
    "Experiment",
    "ExperimentPoint",
    "ExperimentSource",
    "IndicatorPassport",
    "IndicatorProcessingResult",
    "INDICATOR_AGGREGATION_COLUMNS",
    "ManualAuditEvent",
    "MANUAL_DRAFT_SCHEMA_V1_0",
    "MANUAL_DRAFT_SCHEMA_V1_1",
    "MANUAL_DRAFT_SCHEMA_VERSION",
    "ManualDraft",
    "ManualIndicatorPassport",
    "ManualLegacyIndicatorCommon",
    "ManualExperimentSource",
    "ManualInputBundle",
    "ManualPassport",
    "ManualPoint",
    "ManualReinforcement",
    "ManualValidationResult",
    "migrate_manual_draft_payload",
    "ModulusMethodProfile",
    "ModulusOverrides",
    "ModulusResolution",
    "PairingResolution",
    "failure_summary",
    "evaluate_indicator_verification",
    "fit_segmented_pcr",
    "fit_indicator_plane",
    "group_mean_curve",
    "hysteresis_metrics",
    "indicator_audit_frame",
    "indicator_aggregation_frame",
    "indicator_event_frame",
    "indicator_passport_frame",
    "get_modulus_profile",
    "MeasuredPoint",
    "modulus_profile_definitions",
    "modulus_profile_ids",
    "ProcessingConfig",
    "Project",
    "ProvenanceRecord",
    "RawCell",
    "RawRow",
    "build_provenance",
    "metrology_evaluations_from_passports",
    "adapt_manual_draft",
    "parse_decimal",
    "passport_completeness",
    "prepare_measurements",
    "parse_pressure_range",
    "process_indicator_frame",
    "read_protocol",
    "read_protocol_excel",
    "resolve_indicator_passport",
    "resolve_settlement_aggregation",
    "resolve_pairing_design",
    "resolve_modulus_method",
    "SETTLEMENT_AGGREGATIONS",
    "SETTLEMENT_MISSING_CHANNEL_POLICIES",
    "validate_measurements",
    "validate_manual_draft",
]

__version__ = VERSION
