"""Russian, display-only column labels grouped by UI table purpose."""

from __future__ import annotations


COMMON_COLUMN_LABELS_RU: dict[str, str] = {
    "schema_version": "Версия схемы",
    "algorithm_version": "Версия алгоритма",
    "contract_version": "Версия контракта",
    "program_version": "Версия программы",
    "revision": "Ревизия",
    "row_index": "Индекс строки",
    "test_id": "Испытание",
    "project_id": "Идентификатор проекта",
    "dataset_id": "Набор данных",
    "project": "Проект",
    "project_passport": "Паспорт проекта",
    "operator": "Оператор",
    "laboratory_or_site": "Лаборатория или площадка",
    "experiment_date": "Дата испытания",
    "tests": "Испытания",
    "soil": "Грунт",
    "soil_type": "Тип грунта",
    "soil_batch": "Партия грунта",
    "batch": "Партия",
    "box": "Контейнер",
    "density_kg_m3": "Плотность, кг/м³",
    "dry_density_kg_m3": "Плотность сухого грунта, кг/м³",
    "gamma_kN_m3": "Удельный вес γ, кН/м³",
    "moisture_percent": "Влажность, %",
    "water_content_percent": "Содержание воды, %",
    "poisson_ratio": "Коэффициент Пуассона грунта ν",
    "gradation": "Гранулометрический состав",
    "stamp": "Штамп",
    "stamp_mass_kg": "Масса штампа, кг",
    "distance_to_wall_mm": "Расстояние до стенки, мм",
    "tray_dimensions_mm": "Размеры лотка, мм",
    "reinforcement": "Армирование",
    "reinforcement_status": "Статус армирования",
    "material": "Материал",
    "layers": "Количество слоёв",
    "length_mm": "Длина, мм",
    "width_mm": "Ширина, мм",
    "height_mm": "Высота, мм",
    "h_over_D": "Отношение h/D",
    "l_over_D": "Отношение l/D",
    "tensile_strength_kN_m": "Прочность при растяжении, кН/м",
    "instruments": "Приборы",
    "type": "Тип",
    "model": "Модель",
    "calibration_date": "Дата калибровки",
    "resolution_mm": "Разрешение, мм",
    "expanded_uncertainty_mm": "Расширенная неопределённость, мм",
    "indicator_positions_mm": "Координаты индикаторов, мм",
    "indicator_model": "Модель индикатора",
    "indicator_unit": "Единица показаний индикатора",
    "indicator_resolution_mm": "Разрешение индикатора, мм",
    "indicator_calibration_factor": "Коэффициент калибровки индикатора",
    "indicator_sign": "Знак направления индикатора",
    "indicator_instrument_id": "Идентификатор индикатора",
    "reference_sign": "Знак опорного индикатора",
    "load_factor": "Коэффициент пересчёта нагрузки",
    "load_zero": "Нулевая поправка нагрузки",
    "load_resolution_kN": "Разрешение нагрузки, кН",
    "lever_ratio": "Передаточное отношение рычага",
    "publication_curve_selection": "Выбор публикационной кривой",
    "decisions": "Решения",
    "series_name": "Наименование серии",
    "sequence_no": "№ по порядку",
    "sequence_index": "Индекс последовательности",
    "stage": "Ступень",
    "stage_no": "№ ступени",
    "from_sequence": "От точки",
    "to_sequence": "До точки",
    "timestamp": "Время",
    "timestamp_utc": "Время UTC",
    "elapsed_time_s": "Время от начала, с",
    "branch": "Ветвь",
    "branch_suggested": "Предлагаемая ветвь",
    "status": "Статус",
    "level": "Уровень",
    "row_status": "Статус строки",
    "comment": "Комментарий",
    "note": "Примечание",
    "warning": "Предупреждение",
    "info": "Информация",
    "quality_flags": "Признаки качества",
    "severity": "Степень серьёзности",
    "code": "Код",
    "message": "Сообщение",
    "sheet": "Лист проверки",
    "row": "Строка",
    "column": "Столбец",
    "rows": "Строки",
    "suggested_action": "Рекомендуемое действие",
    "blocks_processing": "Блокирует расчёт",
    "entity_id": "Объект проверки",
    "group": "Группа",
    "pair_id": "Идентификатор пары",
    "baseline_group": "Контрольная группа",
    "reinforced_group": "Армированная группа",
    "load_kind": "Вид нагрузки",
    "correction_mode": "Режим коррекции",
    "load_unit": "Единица нагрузки",
    "load_raw": "Нагрузка: исходное значение",
    "raw_load": "Нагрузка: исходная ячейка",
    "parsed_load": "Нагрузка: распознанное значение",
    "formula": "Формула пересчёта",
    "F_kN": "Сила, кН",
    "p_kPa": "Давление, кПа",
    "p_mid_kPa": "Среднее давление, кПа",
    "settlement_unit": "Единица осадки",
    "settlement_raw_mm": "Осадка до коррекции, мм",
    "settlement_mm": "Осадка, мм",
    "settlement_effective_mm": "Расчётная осадка, мм",
    "is_measured": "Осадка измерена",
    "is_failure": "Признак разрушения",
    "stamp_shape": "Форма штампа",
    "stamp_diameter_mm": "Диаметр штампа, мм",
    "stamp_area_m2": "Площадь штампа, м²",
    "sheet_name": "Лист источника",
    "source_type": "Тип источника",
    "format": "Формат",
    "encoding": "Кодировка",
    "delimiter": "Разделитель полей",
    "separator": "Разделитель значений",
    "import_mode": "Режим импорта",
    "sheet_scope": "Область листов",
    "header_row": "Строка заголовков",
    "column_mapping": "Сопоставление столбцов",
    "source_path": "Путь к источнику",
    "source_file": "Исходный файл",
    "source_row": "Строка источника",
    "source_index": "Индекс источника",
    "source_columns": "Исходные столбцы",
    "source_sha256": "SHA-256 источника",
    "before_hash": "SHA-256 до изменения",
    "after_hash": "SHA-256 после изменения",
    "input_file_sha256": "SHA-256 входного файла",
    "metadata_sha256": "SHA-256 metadata",
    "config_sha256": "SHA-256 настроек",
    "source_tree_sha256": "SHA-256 исходного дерева",
    "raw_stage": "Ступень: исходная ячейка",
    "parsed_stage": "Ступень: распознанное значение",
    "raw_indicator": "Индикатор: исходная ячейка",
    "parsed_indicator": "Индикатор: распознанное значение",
    "raw_value": "Исходное значение",
    "parsed_value": "Распознанное значение",
    "field": "Поле",
    "value": "Значение",
    "filled": "Заполнено",
    "created_by": "Создал",
    "created_at": "Создано",
    "modified_by": "Изменил",
    "modified_at": "Изменено",
    "manual_row_uuid": "Идентификатор ручной строки",
    "channel": "Канал",
    "indicator_type": "Тип индикатора",
    "serial_number": "Заводской номер",
    "instrument_id": "Идентификатор прибора",
    "mode": "Режим шкалы",
    "indicator_mode": "Режим индикатора",
    "range_mm": "Диапазон, мм",
    "division_mm": "Цена деления, мм",
    "correction_factor": "Поправочный коэффициент",
    "initial_reading": "Начальное показание",
    "initial_turn": "Начальный номер оборота",
    "zero_correction_mm": "Коррекция нуля, мм",
    "verification_date": "Дата поверки",
    "verification_valid_until": "Поверка действительна до",
    "verification_status": "Статус поверки",
    "verification_evaluation_date": "Дата оценки поверки",
    "verification_evaluation_date_source": "Источник даты оценки",
    "verification_evaluation_rule": "Правило оценки поверки",
    "assignment_status": "Статус назначения",
    "max_increment_mm": "Максимальное приращение, мм",
    "reverse_tolerance_mm": "Допуск обратного хода, мм",
    "travel_range_mm": "Допустимый ход, мм",
    "x_mm": "Координата X, мм",
    "y_mm": "Координата Y, мм",
    "compatibility_mode": "Режим совместимости",
    "original_reading": "Исходное показание",
    "raw_reading": "Показание шкалы",
    "turn_number": "Номер оборота",
    "computed_increment_mm": "Вычисленное приращение, мм",
    "cumulative_before_correction_mm": "Накопленная осадка до коррекции, мм",
    "applied_correction_mm": "Применённая коррекция, мм",
    "cumulative_settlement_mm": "Накопленная осадка, мм",
    "processing_status": "Статус обработки",
    "conversion_method": "Способ преобразования",
    "correction_record_ids": "Записи о коррекциях",
    "event_type": "Тип события",
    "event_id": "Идентификатор события",
    "raw_before": "Показание до события",
    "raw_after": "Показание после события",
    "turn_before": "Оборот до события",
    "turn_after": "Оборот после события",
    "increment_mm": "Приращение, мм",
    "correction_mm": "Коррекция, мм",
    "candidate_turns": "Допустимые номера оборотов",
    "aggregation_method": "Способ агрегации",
    "settlement_aggregation": "Настройка агрегации осадки",
    "channels_required": "Требуемые каналы",
    "channels_used": "Использованные каналы",
    "missing_channels": "Отсутствующие каналы",
    "aggregation_status": "Статус агрегации",
    "settlement_missing_channel_policy": "Настройка обработки пропущенных каналов",
    "missing_channel_policy": "Политика пропусков каналов",
    "aggregated_settlement_mm": "Агрегированная осадка, мм",
    "reference_correction_mm": "Поправка опорного индикатора, мм",
    "plane_rank": "Ранг плоскости",
    "plane_residual_rms_mm": "СКО невязки плоскости, мм",
    "tilt_magnitude_mm_per_mm": "Модуль наклона, мм/мм",
    "tilt_direction_deg": "Направление наклона, °",
    "tilt_direction_resolved": "Направление наклона определено",
    "failure_reached": "Разрушение достигнуто",
    "failure_observed": "Разрушение зафиксировано",
    "interval_censored": "Интервальное цензурирование",
    "right_censored": "Цензурирование справа",
    "censoring_type": "Тип цензурирования",
    "classification_status": "Статус классификации",
    "classification_warning": "Замечание классификации",
    "capacity_kind": "Вид предельной нагрузки",
    "capacity_unit": "Единица предельной нагрузки",
    "lower_bound": "Нижняя граница",
    "upper_bound": "Верхняя граница",
    "capacity_lower": "Нижняя граница несущей способности",
    "capacity_upper": "Верхняя граница несущей способности",
    "capacity_lower_inclusive": "Нижняя граница несущей способности включена",
    "capacity_upper_inclusive": "Верхняя граница несущей способности включена",
    "lower_inclusive": "Нижняя граница включена",
    "upper_inclusive": "Верхняя граница включена",
    "F_last_stable": "Последняя устойчивая сила, кН",
    "F_failure_step": "Сила на ступени разрушения, кН",
    "Fu_lower": "Нижняя граница Fu, кН",
    "Fu_upper": "Верхняя граница Fu, кН",
    "p_last_stable": "Последнее устойчивое давление, кПа",
    "p_failure_step": "Давление на ступени разрушения, кПа",
    "pu_lower": "Нижняя граница pu, кПа",
    "pu_upper": "Верхняя граница pu, кПа",
    "s_last_stable": "Осадка последней устойчивой точки, мм",
    "s_failure": "Осадка при разрушении, мм",
    "failure_sequence_no": "№ ступени разрушения",
    "last_stable_sequence_no": "№ последней устойчивой ступени",
    "failure_event_count": "Количество событий разрушения",
    "lower_bound_sequence_no": "№ ступени нижней границы",
    "upper_bound_sequence_no": "№ ступени верхней границы",
    "display": "Результат",
    "method": "Метод",
    "pcr_auto": "pcr автоматически, кПа",
    "pcr_manual": "pcr подтверждённое, кПа",
    "pcr_effective": "pcr принятое, кПа",
    "pcr_ci_low": "Нижняя граница 95% ДИ pcr, кПа",
    "pcr_ci_high": "Верхняя граница 95% ДИ pcr, кПа",
    "intercept": "Свободный член",
    "slope_before": "Наклон до pcr",
    "slope_after": "Наклон после pcr",
    "hinge_delta": "Изменение наклона",
    "r2": "R²",
    "aic": "AIC",
    "bic": "BIC",
    "n": "Количество точек",
    "used_indices": "Использованные строки",
    "difference_mm": "Разность осадок, мм",
    "ds_dp_mm_per_kPa": "Приращение осадки ds/dp, мм/кПа",
    "dp_ds_kPa_per_mm": "Жёсткость dp/ds, кПа/мм",
    "crossing": "Пересечение",
    "W_total_kJ_m2": "Полная работа деформации, кДж/м²",
    "integrated_segments": "Проинтегрировано сегментов",
    "skipped_gaps": "Пропущено разрывов данных",
    "W_loading_kJ_m2": "Работа при нагружении, кДж/м²",
    "W_hold_kJ_m2": "Работа при выдержке, кДж/м²",
    "W_unloading_kJ_m2": "Работа при разгрузке, кДж/м²",
    "W_reloading_kJ_m2": "Работа при повторном нагружении, кДж/м²",
    "W_cyclic_kJ_m2": "Работа на циклической ветви, кДж/м²",
    "W_unknown_kJ_m2": "Работа на неопределённой ветви, кДж/м²",
    "s_peak_mm": "Пиковая осадка, мм",
    "s_residual_mm": "Остаточная осадка, мм",
    "s_recoverable_mm": "Восстанавливаемая осадка, мм",
    "residual_pressure_kPa": "Давление при остаточной осадке, кПа",
    "hysteresis_energy_kJ_m2": "Энергия гистерезиса, кДж/м²",
    "loop_closed": "Контур гистерезиса замкнут",
    "bootstrap_valid": "Допустимых bootstrap-реализаций",
    "manual_reason": "Причина ручного решения",
    "manual_author": "Автор ручного решения",
    "manual_confirmed_at_utc": "Время подтверждения UTC",
    "E_stamp_app_kPa": "Условный модуль E, кПа",
    "p_min_kPa": "Нижняя граница диапазона E, кПа",
    "p_max_kPa": "Верхняя граница диапазона E, кПа",
    "requested_p_min_kPa": "Запрошенная нижняя граница E, кПа",
    "requested_p_max_kPa": "Запрошенная верхняя граница E, кПа",
    "ci_low_kPa": "Нижняя граница 95% ДИ E, кПа",
    "ci_high_kPa": "Верхняя граница 95% ДИ E, кПа",
    "nu": "Коэффициент Пуассона ν",
    "shape_factor": "Коэффициент формы",
    "slope_m_per_kPa": "Наклон ds/dp, м/кПа",
    "profile_id": "Методический профиль",
    "profile_version": "Версия профиля",
    "is_primary": "Основной результат",
    "review_status": "Статус проверки",
    "p_range_source": "Источник диапазона давления",
    "p_range_origin": "Происхождение диапазона",
    "profile_source": "Источник профиля",
    "nu_source": "Источник ν",
    "shape_factor_source": "Источник коэффициента формы",
    "methodology_note": "Методическое примечание",
    "s_baseline_mm": "Осадка контрольной группы, мм",
    "s_reinforced_mm": "Осадка армированной группы, мм",
    "k_s": "Коэффициент снижения осадки",
    "k_s_ci_low": "Нижняя граница 95% ДИ kₛ",
    "k_s_ci_high": "Верхняя граница 95% ДИ kₛ",
    "delta_s_mm": "Разность осадок, мм",
    "delta_s_ci_low_mm": "Нижняя граница 95% ДИ разности, мм",
    "delta_s_ci_high_mm": "Верхняя граница 95% ДИ разности, мм",
    "settlement_reduction_percent": "Снижение осадки, %",
    "n_baseline": "Испытаний в контрольной группе",
    "n_reinforced": "Испытаний в армированной группе",
    "n_pairs": "Количество пар",
    "analysis_design": "Схема анализа",
    "pairing_status": "Статус парного сопоставления",
    "pairing_reason": "Основание выбора схемы",
    "pairing_warning": "Предупреждение о сопоставлении",
    "pair_ids_used": "Использованные пары",
    "effect_size": "Размер эффекта",
    "effect_size_name": "Метрика размера эффекта",
    "effect_size_ci_low": "Нижняя граница 95% ДИ эффекта",
    "effect_size_ci_high": "Верхняя граница 95% ДИ эффекта",
    "permutation_p": "Пермутационное p-значение",
    "permutation_p_fdr_bh": "p-значение после FDR BH",
    "action": "Действие",
    "user": "Пользователь",
    "scope": "Объект",
    "parameters": "Параметры",
    "old_value": "Предыдущее значение",
    "new_value": "Новое значение",
    "before_value": "Значение до изменения",
    "after_value": "Значение после изменения",
    "author": "Автор",
    "reason": "Причина",
    "git_commit": "Commit Git",
    "git_dirty": "Есть незакоммиченные изменения",
    "python_version": "Версия Python",
    "dependency_versions": "Версии зависимостей",
    "processing_timestamp_utc": "Время обработки UTC",
    "metrology_evaluations": "Оценки метрологии",
    "protocol_type": "Тип протокола",
    "test_scope": "Вид испытания",
    "indicator_1_raw": "Индикатор 1: показание",
    "indicator_2_raw": "Индикатор 2: показание",
    "indicator_3_raw": "Индикатор 3: показание",
    "indicator_4_raw": "Индикатор 4: показание",
}


TABLE_COLUMN_LABELS_RU: dict[str, dict[str, str]] = {
    "protocol": {
        "status": "Статус точки",
        "source_row": "Строка исходного протокола",
    },
    "qc": {
        "status": "Статус проверки",
        "rows": "Строки",
        "column": "Столбец",
    },
    "indicator_passports": {
        "mode": "Режим шкалы",
        "source_path": "Источник паспорта",
    },
    "indicator_processing": {
        "status": "Статус обработки",
        "source_row": "Строка протокола",
        "method": "Способ преобразования",
    },
    "indicator_events": {
        "method": "Способ преобразования",
    },
    "aggregation": {
        "status": "Статус агрегации",
        "row_index": "Индекс строки",
    },
    "failure": {
        "status": "Статус классификации",
    },
    "pcr": {
        "method": "Метод определения pcr",
    },
    "moduli": {
        "method": "Метод расчёта E",
    },
    "group_comparison": {
        "status": "Статус сравнения",
    },
    "audit": {
        "method": "Метод операции",
        "timestamp_utc": "Время записи UTC",
    },
    "provenance_summary": {
        "source_type": "Источник данных",
    },
    "manual_entry": {
        "load_raw": "Введённая нагрузка",
        "comment": "Комментарий оператора",
    },
    "report": {
        "status": "Статус отчёта",
    },
}


TABLE_VALUE_DOMAINS_RU: dict[str, dict[str, str]] = {
    "generic": {
        "correction_mode": "correction",
        "source_type": "import",
        "import_mode": "import",
        "graph_mode": "graph",
        "curve_method": "curve",
        "ci_method": "ci_method",
        "load_kind": "load_kind",
        "test_scope": "test_scope",
        "protocol_type": "protocol_type",
        "stamp_shape": "stamp_shape",
        "channel": "channel",
        "cumulative_sign": "cumulative_sign",
        "mode": "indicator_mode",
        "indicator_mode": "indicator_mode",
        "metrology_status": "metrology",
        "aggregation_method": "aggregation",
        "settlement_aggregation": "aggregation",
        "missing_channel_policy": "missing_policy",
        "settlement_missing_channel_policy": "missing_policy",
        "branch": "branch",
        "branch_suggested": "branch",
        "row_status": "row_status",
        "level": "status",
        "severity": "status",
        "warning": "audit",
        "quality_flags": "audit",
        "status": "status",
        "processing_status": "status",
        "aggregation_status": "status",
        "verification_status": "status",
        "assignment_status": "status",
        "classification_status": "review",
        "review_status": "review",
        "failure_status": "failure",
        "censoring_type": "censoring",
        "capacity_kind": "load_kind",
        "profile_id": "methodology_profile",
        "p_range_source": "range_source",
        "method": "method",
        "conversion_method": "method",
        "event_type": "audit",
        "action": "audit",
        "group": "group",
        "analysis_design": "method",
        "pairing_status": "status",
    },
    "protocol": {
        "status": "row_status",
    },
    "indicator_passports": {
        "mode": "indicator_mode",
        "verification_status": "status",
        "assignment_status": "metrology",
    },
    "indicator_processing": {
        "conversion_method": "method",
    },
    "indicator_events": {
        "event_type": "audit",
        "method": "method",
    },
    "failure": {
        "censoring_type": "censoring",
        "classification_status": "review",
        "capacity_kind": "load_kind",
    },
    "moduli": {
        "profile_id": "methodology_profile",
        "review_status": "review",
        "method": "method",
    },
    "group_comparison": {
        "baseline_group": "group",
        "reinforced_group": "group",
        "analysis_design": "method",
        "pairing_status": "status",
    },
    "audit": {
        "action": "audit",
        "method": "method",
        "status": "status",
    },
    "provenance_summary": {
        "source_type": "import",
        "status": "status",
    },
    "manual_entry": {
        "branch": "branch",
        "row_status": "row_status",
        "load_kind": "load_kind",
        "stamp_shape": "stamp_shape",
        "mode": "indicator_mode",
        "metrology_status": "metrology",
        "settlement_aggregation": "aggregation",
        "settlement_missing_channel_policy": "missing_policy",
    },
    "report": {
        "status": "report",
        "review_status": "review",
    },
}


TABLE_KIND_ALIASES_RU: dict[str, str] = {
    "raw_protocol": "protocol",
    "chronological_protocol": "protocol",
    "quality_control": "qc",
    "issues": "qc",
    "indicator_passport": "indicator_passports",
    "indicator_calibration_parameters": "indicator_passports",
    "indicator_audit": "indicator_processing",
    "indicator_processing_audit": "indicator_processing",
    "indicator_processing_events": "indicator_events",
    "indicator_aggregation": "aggregation",
    "indicator_aggregation_results": "aggregation",
    "failure_summary": "failure",
    "failure_censoring": "failure",
    "pcr_results": "pcr",
    "e": "moduli",
    "e/moduli": "moduli",
    "modulus": "moduli",
    "modulus_results": "moduli",
    "comparison": "group_comparison",
    "group_comparisons": "group_comparison",
    "audit_trail": "audit",
    "provenance": "provenance_summary",
    "manual": "manual_entry",
    "manual_editor": "manual_entry",
}


# Compatibility aliases with intentionally explicit names.
COLUMN_LABELS_RU = COMMON_COLUMN_LABELS_RU
VALUE_DOMAINS_RU = TABLE_VALUE_DOMAINS_RU
