"""Russian display labels for canonical Soil Stamp machine tokens.

The dictionaries in this module are presentation metadata only.  Canonical
values remain the source of truth for calculations, schemas and exports.
"""

from __future__ import annotations

from typing import Any


ENUM_LABELS_RU: dict[str, dict[str, str]] = {
    "correction": {
        "raw": "Исходные данные",
        "zero_shifted": "Нулевой уровень по измеренной точке",
        "seating_corrected": "С посадочной поправкой",
    },
    "import": {
        "strict": "Строгий импорт",
        "interactive": "Сопоставление столбцов",
        "heuristic": "Совместимость со старым форматом",
        "manual": "Ручной ввод",
        "csv": "CSV",
        "xlsx": "Excel",
        "excel": "Excel",
        "protocol": "Файл протокола",
        "equivalence": "Проверка эквивалентности",
        "manual_equivalence": "Проверка ручного ввода",
        "unknown": "Источник не определён",
    },
    "graph": {
        "raw_protocol": "Протокол испытания",
        "antonov_publication": "Публикационный график по Антонову",
        "group_mean_ci": "Средняя кривая и 95% доверительный интервал",
        "diagnostic": "Диагностика критического давления",
        "normalized": "Нормированные координаты",
    },
    "curve": {
        "mean_curve": "Средняя кривая",
        "median_curve": "Медианная кривая",
        "manual_representative": "Выбранный инженером опыт",
        "individual_curves": "Все индивидуальные кривые",
        "normalized": "Нормированные координаты",
    },
    "load_kind": {
        "force": "Сила",
        "pressure": "Давление",
        "unknown": "Вид нагрузки не определён",
    },
    "ci_method": {
        "t": "Доверительный интервал Стьюдента",
        "simultaneous_bootstrap": "Одновременный бутстреп-интервал",
    },
    "range_source": {
        "explicit": "Задан явно",
        "accepted_pcr": "По подтверждённому pcr",
        "project_profile": "Из профиля проекта",
    },
    "test_scope": {
        "laboratory": "Лабораторное испытание",
        "field": "Полевое испытание",
    },
    "protocol_type": {
        "static_step": "Статическое ступенчатое нагружение",
        "load_unload": "Нагружение и разгрузка",
        "cyclic": "Циклическое нагружение",
        "custom": "Другой тип протокола",
    },
    "stamp_shape": {
        "circle": "Круглый штамп",
        "custom": "Другая форма",
    },
    "indicator_mode": {
        "increasing": "Прямая шкала",
        "increasing_wrapped": "Прямая шкала с переходом через ноль",
        "decreasing": "Обратная шкала",
        "decreasing_wrapped": "Обратная шкала с переходом через ноль",
        "cumulative_settlement": "Готовая накопленная осадка",
    },
    "cumulative_sign": {
        "1": "Положительное направление (+1)",
        "-1": "Отрицательное направление (−1)",
    },
    "channel": {
        "": "Не выбран",
        "indicator_1": "Индикатор 1",
        "indicator_2": "Индикатор 2",
        "indicator_3": "Индикатор 3",
        "indicator_4": "Индикатор 4",
        "reference_indicator": "Опорный индикатор",
    },
    "editor_column": {
        "sequence_no": "№ по порядку",
        "stage_no": "№ ступени",
        "branch": "Ветвь",
        "elapsed_time_s": "Время от начала, с",
        "timestamp": "Время",
        "load_raw": "Исходное значение нагрузки",
        "indicator_1_raw": "Показание индикатора 1",
        "indicator_2_raw": "Показание индикатора 2",
        "indicator_3_raw": "Показание индикатора 3",
        "indicator_4_raw": "Показание индикатора 4",
        "row_status": "Статус строки",
        "comment": "Комментарий",
    },
    "metrology": {
        "draft": "Черновик",
        "review_required": "Требуется проверка",
        "confirmed": "Подтверждено",
        "migration_review_required": "Проверка после переноса данных",
    },
    "status": {
        "draft": "Черновик",
        "review_required": "Требуется проверка",
        "confirmed": "Подтверждено",
        "migration_review_required": "Проверка после переноса данных",
        "ok": "Без замечаний",
        "pass": "Пройдено",
        "passed": "Пройдено",
        "fail": "Не пройдено",
        "failed": "Не пройдено",
        "error": "Ошибка",
        "warning": "Предупреждение",
        "info": "Информация",
        "valid": "Допустимо",
        "invalid": "Недопустимо",
        "missing": "Нет данных",
        "unprocessed": "Не обработано",
        "unresolved": "Не определено",
        "complete": "Завершено",
        "pending": "Ожидает выполнения",
        "ready_for_review": "Готово к проверке",
        "valid_at_experiment": "Поверка действительна на дату испытания",
        "not_yet_valid_at_experiment": "Поверка ещё не действует на дату испытания",
        "expired_at_experiment": "Поверка истекла на дату испытания",
        "blocked_invalid_policy": "Расчёт заблокирован: недопустимая политика",
        "blocked_missing_channels": "Расчёт заблокирован: недостаточно каналов",
        "blocked_collinear_geometry": "Расчёт заблокирован: вырожденная геометрия",
        "no_aggregation": "Агрегация не выполняется",
        "not_applied_direct_settlement": "Не применяется для непосредственно заданной осадки",
        "paired_validated": "Парное сопоставление подтверждено",
        "independent_fallback": "Независимый анализ",
        "candidate_for_engineering_acceptance": "Кандидат на инженерную приёмку",
    },
    "aggregation": {
        "all_channels_mean": "Среднее по всем каналам",
        "selected_channels_mean": "Среднее по выбранным каналам",
        "plane_center": "Осадка в центре по плоскости",
        "primary_channel": "Основной канал",
        "no_aggregation": "Без агрегации",
        "unresolved": "Агрегация не определена",
    },
    "missing_policy": {
        "block": "Блокировать расчёт",
        "allow_if_solvable": "Разрешить при достаточных данных",
        "unresolved": "Политика не определена",
    },
    "branch": {
        "loading": "Нагружение",
        "hold": "Выдержка",
        "unloading": "Разгрузка",
        "reloading": "Повторное нагружение",
        "cyclic": "Циклическая ветвь",
    },
    "row_status": {
        "measurement": "Измерение",
        "failure": "Разрушение",
        "instrument_limit": "Предел хода индикатора",
        "stopped_without_failure": "Остановлено без разрушения",
        "invalid": "Недопустимая строка",
        "ok": "Измерение принято",
        "stable": "Стабилизированная точка",
        "accepted": "Принятая точка",
        "valid": "Допустимая точка",
    },
    "failure": {
        "measurement": "Измерение",
        "failure": "Разрушение",
        "failure_observed": "Разрушение зафиксировано",
        "failure_without_settlement": "Разрушение без измеренной осадки",
        "instrument_limit": "Предел хода индикатора",
        "stopped_without_failure": "Остановлено без разрушения",
        "reached": "Разрушение достигнуто",
        "not_reached": "Разрушение не достигнуто",
        "observed": "Зафиксировано",
        "not_observed": "Не зафиксировано",
        "invalid": "Недопустимая строка",
    },
    "censoring": {
        "interval_censored": "Интервально цензурировано",
        "interval-observed": "Разрушение в интервале",
        "right_censored": "Цензурировано справа",
        "indeterminate": "Тип цензурирования не определён",
        "none": "Без сводной оценки",
        "failure": "Разрушение",
        "failure_observed": "Разрушение зафиксировано",
    },
    "methodology_profile": {
        "antonov_round_stamp_v1": "Антонов: круглый штамп (версия 1)",
        "custom_v1": "Пользовательский профиль (версия 1)",
        "diagnostic_unapproved_v1": "Диагностический профиль без утверждения (версия 1)",
    },
    "method": {
        "bounded": "Ограниченная сегментированная аппроксимация",
        "independent_two_line_bic": "Две независимые прямые по BIC",
        "continuous_segmented_hinge": "Непрерывная сегментированная модель",
        "manual_confirmation": "Подтверждено инженером вручную",
        "methodology_resolver": "Разрешение методического профиля",
        "e_regression": "Модуль E по линейной регрессии",
        "e_secant": "Секущий модуль E",
        "explicit_turn_number": "Явно заданный номер оборота",
        "non_wrapped_scale": "Шкала без перехода через ноль",
        "automatic_unique_turn_candidate": "Однозначно определённый переход через ноль",
        "automatic_unique_reverse_candidate": "Однозначно определённый обратный переход",
        "blocked_no_unique_turn": "Преобразование заблокировано: оборот неоднозначен",
        "preserve_nan": "Сохранение пропущенного значения NaN",
        "unresolved": "Способ не определён",
        "cumulative_settlement": "Готовая накопленная осадка",
        "none": "Не применяется",
        "mean": "Среднее",
        "median": "Медиана",
        "paired": "Парный анализ",
        "independent": "Независимый анализ",
    },
    "review": {
        "ok": "Без замечаний",
        "draft": "Черновик",
        "review_required": "Требуется проверка",
        "migration_review_required": "Проверка после переноса данных",
        "confirmed": "Подтверждено",
        "approved": "Утверждено",
        "accepted": "Принято",
        "signed": "Подписано",
        "unsigned": "Не подписано",
        "approved_for_conditional_calculation": "Разрешён условный расчёт",
        "requires_project_approval": "Требуется утверждение проекта",
        "unapproved": "Не утверждено",
        "ready_for_review": "Готово к проверке",
    },
    "group": {
        "baseline": "Контрольная группа",
        "reinforced": "Армированная группа",
    },
    "report": {
        "ready_for_review": "Отчёт готов к проверке",
        "review_required": "Отчёт требует проверки",
        "generated": "Отчёт сформирован",
        "complete": "Комплект сформирован",
        "candidate_for_engineering_acceptance": "Кандидат на инженерную приёмку",
        "technical_pass": "Технические проверки пройдены",
    },
    "audit": {
        "import_dataset": "Импорт набора данных",
        "select_publication_curve": "Выбор публикационной кривой",
        "load_publication_curve_selection": "Загрузка решения о публикационной кривой",
        "configure_failure_analysis": "Настройка анализа разрушения",
        "resolve_modulus_method": "Выбор методики расчёта E",
        "update_passport": "Изменение паспорта",
        "invalidate_metrology_confirmation": "Отмена подтверждения метрологии",
        "reject_metrology_confirmation": "Отклонение подтверждения метрологии",
        "reconfirm_metrology_after_update": "Повторное подтверждение метрологии",
        "copy_indicator_passport": "Копирование паспорта индикатора",
        "add_row": "Добавление строки",
        "insert_before": "Вставка строки перед выбранной",
        "insert_after": "Вставка строки после выбранной",
        "delete_row": "Удаление строки",
        "duplicate_row": "Дублирование строки",
        "renumber": "Перенумерация строк",
        "fill_stages": "Заполнение номеров ступеней",
        "paste_add_row": "Добавление строки при вставке",
        "paste_cell": "Вставка значения в ячейку",
        "paste_block": "Вставка блока",
        "clear_cell": "Очистка ячейки",
        "clear_cells": "Очистка диапазона",
        "editor_add_row": "Добавление строки в редакторе",
        "editor_cell_edit": "Изменение ячейки в редакторе",
        "editor_delete_row": "Удаление строки в редакторе",
        "editor_reorder_rows": "Изменение порядка строк",
        "apply_editor_frame": "Применение изменений таблицы",
        "activate_analysis_snapshot": "Передача снимка в анализ",
        "zero_crossing": "Переход через ноль",
        "zero_correction_applied": "Применена коррекция нуля",
        "explicit_turn_number": "Явно задан номер оборота",
        "small_reverse_motion": "Небольшой обратный ход",
        "unexpected_reverse_motion": "Недопустимый обратный ход",
        "invalid_jump": "Недопустимый скачок",
        "travel_range_exceeded": "Превышен диапазон хода",
        "missing_reading": "Показание отсутствует",
        "repeated_reading": "Показание повторяется",
        "create": "Создание",
        "update": "Изменение",
        "delete": "Удаление",
        "undo": "Отмена изменения",
        "redo": "Повтор изменения",
        "import": "Импорт",
        "export": "Экспорт",
    },
}


DOMAIN_ALIASES_RU: dict[str, str] = {
    "correction_mode": "correction",
    "import_mode": "import",
    "graph_mode": "graph",
    "curve_method": "curve",
    "curve_selection": "curve",
    "curve_selection_method": "curve",
    "indicator": "indicator_mode",
    "indicator_scale": "indicator_mode",
    "metrology_status": "metrology",
    "metrology/status": "status",
    "aggregation_method": "aggregation",
    "settlement_aggregation": "aggregation",
    "settlement_missing_channel_policy": "missing_policy",
    "failure/censoring": "censoring",
    "failure_censoring": "censoring",
    "profile": "methodology_profile",
    "profile_id": "methodology_profile",
    "methodology": "methodology_profile",
    "methodology_profiles": "methodology_profile",
    "review_status": "review",
    "group_role": "group",
    "report_status": "report",
    "audit_action": "audit",
}


def _normalize_domain(domain: Any) -> str:
    normalized = str(domain or "").strip().casefold().replace("-", "_").replace(" ", "_")
    return DOMAIN_ALIASES_RU.get(normalized, normalized)


def lookup_ru_label(domain: Any, value: Any) -> str:
    """Return a Russian display label, preserving every unknown token verbatim."""

    original = "" if value is None else str(value)
    normalized_value = original.strip().casefold()
    labels = ENUM_LABELS_RU.get(_normalize_domain(domain), {})
    return labels.get(normalized_value, original)


# A short compatibility name for callers that only need the registry.
LABELS_RU = ENUM_LABELS_RU
